Update deps, fix go get error
cilium/ebpf had a breaking API change from 0.1.0 to 0.2.0 (LoadPinnedMap
has an extra parameter). For some reason go get uses 0.2.0 even though
we have 0.1.0 in our go mod, which breaks things:

    go get -u github.com/cloudflare/xdpcap/cmd/xdpcap
    go: downloading github.com/cloudflare/xdpcap v0.0.0-20201119121328-12307bddefb8
    go: downloading github.com/cilium/ebpf v0.2.0

        github.com/cloudflare/xdpcap/cmd/xdpcap
        go/pkg/mod/github.com/cloudflare/xdpcap@v0.0.0-20201119121328-12307bddefb8/cmd/xdpcap/filter.go:44:36: not enough arguments in call to ebpf.LoadPinnedMap
                have (string)
                want (string, *ebpf.LoadPinOptions)

Update our dependencies to fix this.