Ignore perf.IsClosed(err) on shutdown
When shutting down, calsl to perf.Read() will return a ErrClosed. We
didn't handle these specifically, causing spurious errors on shutdown:

    $ sudo ./xdpcap -buffer 4096 /run/xdpd/bpffs/l4lb foo.pcap
    aborted: 0/0    drop: 0/0       pass: 142801/142801     tx: 0/0 (received/matched packets)
    aborted: 0/0    drop: 0/0       pass: 285453/285453     tx: 0/0 (received/matched packets)
    ^CError: perf reader was closed
    Error: perf reader was closed
    Error: perf reader was closed
    Error: perf reader was closed

Test for perf.IsClosed() to suppress these errors.